In [432]:
import pandas as pd
import numpy as np
import scipy.stats as stats

# Problem1

Calculate and compare the expected value and standard deviation of price at time t (ùëÉ ùë° ), given  each of the 3 types of price returns, assuming ùëü ùë° ‚àº ùëÅ (0, œÉ^2 ). Simulate each return equation  using ùëü ùë° ‚àº ùëÅ (0, œÉ^2 ) and show the mean and standard deviation match your expectations. ùë° ‚àº ùëÅ (0, œÉ^2 )

In [433]:
sigma = 0.2
t = 1
P0 = 100

# Simulate the returns
rt = np.random.normal(0, sigma, 1)
classical_return= rt
arithmetic_return = rt
geometric_return = np.exp(rt) - 1


# Calculate the prices
classical_price= P0 + classical_return
arithmetic_price = P0 * (1 + arithmetic_return)
geometric_price = P0 * np.exp(geometric_return)

# Calculate the expected values and standard deviations
classical_expected = P0
classical_std = np.sqrt(sigma**2)

arithmetic_expected = P0
arithmetic_std = P0 * sigma

geometric_expected = P0 * np.exp(sigma**2/2)
geometric_std = P0 * np.sqrt(np.exp(sigma**2) - 1)

# Print the results
print("Classical price: E(P) = {:.2f}, SD(P) = {:.2f}".format(classical_expected, classical_std))
print("Arithmetic price: E(P) = {:.2f}, SD(P) = {:.2f}".format(arithmetic_expected, arithmetic_std))
print("Geometric price: E(P) = {:.2f}, SD(P) = {:.2f}".format(geometric_expected, geometric_std))

Classical price: E(P) = 100.00, SD(P) = 0.20
Arithmetic price: E(P) = 100.00, SD(P) = 20.00
Geometric price: E(P) = 102.02, SD(P) = 20.20

# Problem2

Implement a function similar to the ‚Äúreturn_calculate()‚Äù in this week‚Äôs code. Allow the user to specify the method of return calculation. 
Use DailyPrices.csv. Calculate the arithmetic returns for all prices. 

Remove the mean from the series so that the mean(META)=0 

Calculate VaR 
1. Using a normal distribution. 
2. Using a normal distribution with an Exponentially Weighted variance (Œª = 0. 94) 
3. Using a MLE fitted T distribution. 
4. Using a fitted AR(1) model. 
5. Using a Historic Simulation. 
Compare the 5 values.

In [434]:
df=pd.read_csv('DailyPrices.csv')
df

,Date,SPY,AAPL,MSFT,AMZN,TSLA,GOOGL,GOOG,META,NVDA,...,PNC,MDLZ,MO,ADI,GILD,LMT,SYK,GM,TFC,TJX
0,2/14/2022 0:00,432.011322,167.863144,292.261475,155.167007,291.920013,135.526001,135.300003,217.699997,242.443298,...,197.263107,64.592575,46.290192,151.118790,58.443172,377.068665,247.324020,48.182598,60.352272,66.789505
1,2/15/2022 0:00,438.978333,171.749573,297.680664,156.510498,307.476654,136.608505,136.425507,221.000000,264.702484,...,199.789520,64.328896,46.502743,159.029022,58.653572,372.440185,255.490829,49.446892,62.076630,67.673614
2,2/16/2022 0:00,439.470337,171.511032,297.333191,158.100494,307.796661,137.738007,137.487503,216.539993,264.862305,...,201.139511,64.172638,46.770744,165.211960,59.198696,377.000458,256.349976,50.203476,61.990410,65.915215
3,2/17/2022 0:00,430.082642,167.863144,288.626679,154.652496,292.116669,132.539002,132.308502,207.710007,244.841064,...,194.109894,64.514450,47.473091,157.448944,58.615318,378.822571,248.439911,48.600708,59.921181,64.019295
4,2/18/2022 0:00,427.297852,166.292648,285.846893,152.601502,285.660004,130.403000,130.467499,206.160004,236.199127,...,193.984528,64.455841,47.815025,157.380234,58.385788,376.571686,245.042847,48.381695,59.700851,64.981995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,2/3/2023 0:00,412.350006,154.264465,258.350006,103.389999,189.979996,104.779999,105.220001,186.529999,211.000000,...,165.389999,65.910004,46.910000,178.820007,84.500000,459.079987,283.140015,41.130001,49.561237,80.222557
245,2/6/2023 0:00,409.829987,151.498688,256.769989,102.180000,194.759995,102.900002,103.470001,186.059998,210.889999,...,163.000000,66.169998,46.959999,177.550003,86.360001,469.100006,271.480011,41.340000,49.076408,79.853935
246,2/7/2023 0:00,415.190002,154.414230,267.559998,102.110001,196.809998,107.639999,108.040001,191.619995,221.729996,...,162.940002,65.080002,46.560001,181.020004,86.050003,468.329987,272.450012,41.400002,49.501869,79.565002
247,2/8/2023 0:00,410.649994,151.688400,266.730011,100.050003,201.289993,99.370003,100.000000,183.429993,222.050003,...,161.559998,64.790001,46.500000,177.759995,85.669998,469.649994,268.220001,41.570000,48.739998,80.309998
248,2/9/2023 0:00,407.089996,150.639999,263.619995,98.239998,207.320007,95.010002,95.459999,177.919998,223.369995,...,158.880005,64.290001,46.330002,178.520004,85.529999,470.089996,264.359985,41.630001,47.930000,80.760002

In [435]:
df.drop('Date', axis=1, inplace=True)
rt=df.pct_change().dropna()

In [436]:
rt_mean=rt.mean()
rt1=rt-rt_mean
rt=rt1.loc[:,'META']
rt

1      0.015175
2     -0.020165
3     -0.040761
4     -0.007446
5     -0.019774
         ...
244   -0.011850
245   -0.002503
246    0.029899
247   -0.042725
248   -0.030022
Name: META, Length: 248, dtype: float64

In [437]:
#Using normal distribution
confidence_level = 0.95
z_alpha = stats.norm.ppf(1 - confidence_level)
var_normal=-(np.sqrt(np.var(rt)) * z_alpha)
print("VaR normal distribution: {}".format(var_normal))

VaR normal distribution: 0.06546917484881118

In [438]:
# Using normal distribution with EWMA variance
ewma_lambda = 0.94
column=pd.DataFrame(column, index=None)
z_alpha = stats.norm.ppf(1 - confidence_level)
ewma_var = rt.ewm(alpha=1-ewma_lambda).var().iloc[-1]
var_ewma=-(float(np.sqrt(ewma_var) * z_alpha))
var_ewma
print("VaR normal distribution with EWMA variance: {}".format(var_ewma))

VaR normal distribution with EWMA variance: 0.0901898406731005

In [439]:
# Using MLE fitted T distribution
t_params = stats.t.fit(rt)
var_t=-stats.t.ppf(0.05, df=t_params[0], loc=t_params[1], scale=t_params[2])
print("VaR MLE fited T distribution: {}".format(var_t))

VaR MLE fited T distribution: 0.057579649751533055

In [440]:
# Using fitted AR(1) model
from statsmodels.tsa.arima.model import ARIMA
n=10000
model = ARIMA(rt, order=(1, 0, 0)).fit()
sigma = np.std(model.resid)
sim_returns = np.empty(n)
returns = rt.values
for i in range(n):
    sim_returns[i] =  model.params[0] * (returns[-1]) + sigma * np.random.normal()
var_AR1 = -np.percentile(sim_returns, 0.05*100)
print("VaR AR(1): {}".format(var_AR1))

/opt/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/base/tsa_model.py:471: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
/opt/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/base/tsa_model.py:471: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
/opt/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/base/tsa_model.py:471: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

VaR AR(1): 0.06534799210310807

In [441]:
# Using historic simulation
num_simulations = 1000
simulated_returns = np.random.choice(rt.squeeze(), size=(num_simulations, len(rt)))
var_historic=(-np.percentile(simulated_returns, (1-confidence_level)*100))
print("VaR historical simulation: {}".format(var_historic))

VaR historical simulation: 0.05590681367337082

# Problem3

Using Portfolio.csv and DailyPrices.csv. Assume the expected return on all stocks is 0.
This file contains the stock holdings of 3 portfolios. You own each of these portfolios. Using an exponentially weighted covariance with lambda = 0.94, calculate the VaR of each portfolio as well as your total VaR (VaR of the total holdings). Express VaR as a $. 

Discuss your methods and your results. 

Choose a different model for returns and calculate VaR again. Why did you choose that model? How did the model change affect the results?

In [442]:
df1=pd.read_csv('DailyPrices.csv')
df1.drop('Date', axis=1, inplace=True)
df1

,SPY,AAPL,MSFT,AMZN,TSLA,GOOGL,GOOG,META,NVDA,BRK-B,...,PNC,MDLZ,MO,ADI,GILD,LMT,SYK,GM,TFC,TJX
0,432.011322,167.863144,292.261475,155.167007,291.920013,135.526001,135.300003,217.699997,242.443298,314.279999,...,197.263107,64.592575,46.290192,151.118790,58.443172,377.068665,247.324020,48.182598,60.352272,66.789505
1,438.978333,171.749573,297.680664,156.510498,307.476654,136.608505,136.425507,221.000000,264.702484,316.200012,...,199.789520,64.328896,46.502743,159.029022,58.653572,372.440185,255.490829,49.446892,62.076630,67.673614
2,439.470337,171.511032,297.333191,158.100494,307.796661,137.738007,137.487503,216.539993,264.862305,315.649994,...,201.139511,64.172638,46.770744,165.211960,59.198696,377.000458,256.349976,50.203476,61.990410,65.915215
3,430.082642,167.863144,288.626679,154.652496,292.116669,132.539002,132.308502,207.710007,244.841064,313.549988,...,194.109894,64.514450,47.473091,157.448944,58.615318,378.822571,248.439911,48.600708,59.921181,64.019295
4,427.297852,166.292648,285.846893,152.601502,285.660004,130.403000,130.467499,206.160004,236.199127,314.799988,...,193.984528,64.455841,47.815025,157.380234,58.385788,376.571686,245.042847,48.381695,59.700851,64.981995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,412.350006,154.264465,258.350006,103.389999,189.979996,104.779999,105.220001,186.529999,211.000000,308.510010,...,165.389999,65.910004,46.910000,178.820007,84.500000,459.079987,283.140015,41.130001,49.561237,80.222557
245,409.829987,151.498688,256.769989,102.180000,194.759995,102.900002,103.470001,186.059998,210.889999,308.429993,...,163.000000,66.169998,46.959999,177.550003,86.360001,469.100006,271.480011,41.340000,49.076408,79.853935
246,415.190002,154.414230,267.559998,102.110001,196.809998,107.639999,108.040001,191.619995,221.729996,312.970001,...,162.940002,65.080002,46.560001,181.020004,86.050003,468.329987,272.450012,41.400002,49.501869,79.565002
247,410.649994,151.688400,266.730011,100.050003,201.289993,99.370003,100.000000,183.429993,222.050003,308.480011,...,161.559998,64.790001,46.500000,177.759995,85.669998,469.649994,268.220001,41.570000,48.739998,80.309998
248,407.089996,150.639999,263.619995,98.239998,207.320007,95.010002,95.459999,177.919998,223.369995,307.209992,...,158.880005,64.290001,46.330002,178.520004,85.529999,470.089996,264.359985,41.630001,47.930000,80.760002

In [443]:
df2=pd.read_csv('Portfolio.csv', index_col=0)
df2

          Stock  Holding
Portfolio
A          AAPL       58
A          TSLA       10
A           JPM       64
A            HD       27
A           BAC      209
...         ...      ...
C             F      397
C          LRCX       14
C            MO      197
C           LMT       27
C           TFC      149

[99 rows x 2 columns]

In [444]:
rt=df1.pct_change().dropna()
rt

,SPY,AAPL,MSFT,AMZN,TSLA,GOOGL,GOOG,META,NVDA,BRK-B,...,PNC,MDLZ,MO,ADI,GILD,LMT,SYK,GM,TFC,TJX
1,0.016127,0.023152,0.018542,0.008658,0.053291,0.007987,0.008319,0.015158,0.091812,0.006109,...,0.012807,-0.004082,0.004592,0.052344,0.003600,-0.012275,0.033021,0.026240,0.028572,0.013237
2,0.001121,-0.001389,-0.001167,0.010159,0.001041,0.008268,0.007784,-0.020181,0.000604,-0.001739,...,0.006757,-0.002429,0.005763,0.038879,0.009294,0.012244,0.003363,0.015301,-0.001389,-0.025984
3,-0.021361,-0.021269,-0.029282,-0.021809,-0.050943,-0.037746,-0.037669,-0.040778,-0.075591,-0.006653,...,-0.034949,0.005326,0.015017,-0.046988,-0.009855,0.004833,-0.030857,-0.031925,-0.033380,-0.028763
4,-0.006475,-0.009356,-0.009631,-0.013262,-0.022103,-0.016116,-0.013914,-0.007462,-0.035296,0.003987,...,-0.000646,-0.000908,0.007203,-0.000436,-0.003916,-0.005942,-0.013674,-0.004506,-0.003677,0.015038
5,-0.010732,-0.017812,-0.000729,-0.015753,-0.041366,-0.004521,-0.008163,-0.019790,-0.010659,-0.002033,...,0.009494,0.007121,-0.008891,0.003243,-0.001147,-0.000673,0.008342,-0.037654,-0.002246,-0.013605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,-0.010629,0.024400,-0.023621,-0.084315,0.009083,-0.027474,-0.032904,-0.011866,-0.028053,-0.010742,...,-0.004694,-0.011251,-0.001277,-0.002677,0.038211,0.004134,0.002336,-0.008916,-0.005954,0.001617
245,-0.006111,-0.017929,-0.006116,-0.011703,0.025161,-0.017942,-0.016632,-0.002520,-0.000521,-0.000259,...,-0.014451,0.003945,0.001066,-0.007102,0.022012,0.021826,-0.041181,0.005106,-0.009782,-0.004595
246,0.013079,0.019245,0.042022,-0.000685,0.010526,0.046064,0.044167,0.029883,0.051401,0.014720,...,-0.000368,-0.016473,-0.008518,0.019544,-0.003590,-0.001641,0.003573,0.001451,0.008669,-0.003618
247,-0.010935,-0.017653,-0.003102,-0.020174,0.022763,-0.076830,-0.074417,-0.042741,0.001443,-0.014346,...,-0.008469,-0.004456,-0.001289,-0.018009,-0.004416,0.002819,-0.015526,0.004106,-0.015391,0.009363
248,-0.008669,-0.006912,-0.011660,-0.018091,0.029957,-0.043876,-0.045400,-0.030039,0.005945,-0.004117,...,-0.016588,-0.007717,-0.003656,0.004275,-0.001634,0.000937,-0.014391,0.001443,-0.016619,0.005603

In [445]:
stock_name=rt.columns.tolist()

Delta Normal VaR

In [446]:
#portfolio A
por1=df2.loc['A']
stock1=por1.iloc[:, 0]
holding1=por1.iloc[:, 1]
weight1=holding1.div(holding1.sum())
return1=[]
for m in stock1.tolist():
    return1.append(rt.loc[:,m].tolist())
    
return1=pd.DataFrame(return1).transpose()
port_return1=return1.dot(np.array(weight1).transpose())

current_value=[]
for m in stock1.tolist():
    col=(df1.loc[:, m]).tolist()
    current_value.append(col[-1])

pv=pd.DataFrame(current_value).values.T@pd.DataFrame(holding1).values
pv=float(pv)

grad_R=[]
for m in range(len(current_value)):
    grad_R.append((current_value[m]/pv)*(holding1.tolist()[m]))


lambda_ = 0.94
cov_ewm = exp_weighted_cov(return1, lambda_=0.94)

var=pv*1.645*np.sqrt(pd.DataFrame(grad_R).T.values@cov_ewm@pd.DataFrame(grad_R).values)
print("Portfolio A VaR: ${:.4f}".format(float(var)))

Portfolio A VaR: $5670.7075

In [447]:
#PortfolioB
por1=df2.loc['B']
stock1=por1.iloc[:, 0]
holding1=por1.iloc[:, 1]
weight1=holding1.div(holding1.sum())
return1=[]
for m in stock1.tolist():
    return1.append(rt.loc[:,m].tolist())
    
return1=pd.DataFrame(return1).transpose()
port_return1=return1.dot(np.array(weight1).transpose())

current_value=[]
for m in stock1.tolist():
    col=(df1.loc[:, m]).tolist()
    current_value.append(col[-1])

pv=pd.DataFrame(current_value).values.T@pd.DataFrame(holding1).values
pv=float(pv)

grad_R=[]
for m in range(len(current_value)):
    grad_R.append((current_value[m]/pv)*(holding1.tolist()[m]))


lambda_ = 0.94
cov_ewm = exp_weighted_cov(return1, lambda_=0.94)

var=pv*1.645*np.sqrt(pd.DataFrame(grad_R).T.values@cov_ewm@pd.DataFrame(grad_R).values)
print("Portfolio B VaR: ${:.4f}".format(float(var)))

Portfolio B VaR: $4494.9984

In [448]:
#PortfolioC
por1=df2.loc['C']
stock1=por1.iloc[:, 0]
holding1=por1.iloc[:, 1]
weight1=holding1.div(holding1.sum())
return1=[]
for m in stock1.tolist():
    return1.append(rt.loc[:,m].tolist())
    
return1=pd.DataFrame(return1).transpose()
port_return1=return1.dot(np.array(weight1).transpose())

current_value=[]
for m in stock1.tolist():
    col=(df1.loc[:, m]).tolist()
    current_value.append(col[-1])

pv=pd.DataFrame(current_value).values.T@pd.DataFrame(holding1).values
pv=float(pv)

grad_R=[]
for m in range(len(current_value)):
    grad_R.append((current_value[m]/pv)*(holding1.tolist()[m]))


lambda_ = 0.94
cov_ewm = exp_weighted_cov(return1, lambda_=0.94)

var=pv*1.645*np.sqrt(pd.DataFrame(grad_R).T.values@cov_ewm@pd.DataFrame(grad_R).values)
print("Portfolio C VaR: {:.4f}".format(float(var)))

Portfolio C VaR: 3786.9260

In [449]:
#Total portfolio
por1=df2
stock1=por1.iloc[:, 0]
holding1=por1.iloc[:, 1]
weight1=holding1.div(holding1.sum())
return1=[]
for m in stock1.tolist():
    return1.append(rt.loc[:,m].tolist())
    
return1=pd.DataFrame(return1).transpose()
port_return1=return1.dot(np.array(weight1).transpose())

current_value=[]
for m in stock1.tolist():
    col=(df1.loc[:, m]).tolist()
    current_value.append(col[-1])

pv=pd.DataFrame(current_value).values.T@pd.DataFrame(holding1).values
pv=float(pv)

grad_R=[]
for m in range(len(current_value)):
    grad_R.append((current_value[m]/pv)*(holding1.tolist()[m]))


lambda_ = 0.94
cov_ewm = exp_weighted_cov(return1, lambda_=0.94)

var=pv*1.645*np.sqrt(pd.DataFrame(grad_R).T.values@cov_ewm@pd.DataFrame(grad_R).values)
print("Total VaR: {:.4f}".format(float(var)))

Total VaR: 13578.2836

Normal Monte Carlo Method

In [450]:
#portfolio value=pv
por1=df2.loc['A']
stock1=por1.iloc[:, 0]
holding1=por1.iloc[:, 1]
weight1=holding1.div(holding1.sum())
return1=[]
for m in stock1.tolist():
    return1.append(rt.loc[:,m].tolist())
   
return1=pd.DataFrame(return1).transpose()
port_return1=return1.dot(np.array(weight1).transpose())

current_value=[]
for m in stock1.tolist():
    col=(df1.loc[:, m]).tolist()
    current_value.append(col[-1])

pv=pd.DataFrame(current_value).values.T@pd.DataFrame(holding1).values
pv=float(pv)
    
#simulate N draws from normal distribution
cov_m=np.cov(np.array(return1).T)
np.random.seed(42)
sim_returns = np.random.multivariate_normal(np.zeros(len(current_value)), cov_m, 10000)

#price each asset from N draws
sim_prices = (1 + sim_returns) * np.array(current_value)
pVals = sim_prices.dot(np.array(holding1))
pVals.sort()

a = int(0.05 * 10000)
VaR = pv - pVals[a]
print("Portfolio A VaR: {:.4f}".format(VaR))

Portfolio A VaR: 8032.5840

In [451]:
#portfolio value=pv
por1=df2.loc['B']
stock1=por1.iloc[:, 0]
holding1=por1.iloc[:, 1]
weight1=holding1.div(holding1.sum())
return1=[]
for m in stock1.tolist():
    return1.append(rt.loc[:,m].tolist())
   
return1=pd.DataFrame(return1).transpose()
port_return1=return1.dot(np.array(weight1).transpose())

current_value=[]
for m in stock1.tolist():
    col=(df1.loc[:, m]).tolist()
    current_value.append(col[-1])

pv=pd.DataFrame(current_value).values.T@pd.DataFrame(holding1).values
pv=float(pv)

#simulate N draws from normal distribution
cov_m=np.cov(np.array(return1).T)
np.random.seed(42)
sim_returns = np.random.multivariate_normal(np.zeros(len(current_value)), cov_m, 10000)

#price each asset from N draws
sim_prices = (1 + sim_returns) * np.array(current_value)
pVals = sim_prices.dot(np.array(holding1))
pVals.sort()

a = int(0.05 * 10000)
VaR = pv - pVals[a]
print("Portfolio B VaR: {:.4f}".format(VaR))

Portfolio B VaR: 6732.9929

In [452]:
#portfolio value=pv
por1=df2.loc['C']
stock1=por1.iloc[:, 0]
holding1=por1.iloc[:, 1]
weight1=holding1.div(holding1.sum())
return1=[]
for m in stock1.tolist():
    return1.append(rt.loc[:,m].tolist())
   
return1=pd.DataFrame(return1).transpose()
port_return1=return1.dot(np.array(weight1).transpose())

current_value=[]
for m in stock1.tolist():
    col=(df1.loc[:, m]).tolist()
    current_value.append(col[-1])

pv=pd.DataFrame(current_value).values.T@pd.DataFrame(holding1).values
pv=float(pv)

#simulate N draws from normal distribution
cov_m=np.cov(np.array(return1).T)
np.random.seed(42)
sim_returns = np.random.multivariate_normal(np.zeros(len(current_value)), cov_m, 10000)

#price each asset from N draws
sim_prices = (1 + sim_returns) * np.array(current_value)
pVals = sim_prices.dot(np.array(holding1))
pVals.sort()

a = int(0.05 * 10000)
VaR = pv - pVals[a]
print("Portfolio C VaR: {:.4f}".format(VaR))

Portfolio C VaR: 5638.2563

In [453]:
por1=df2
stock1=por1.iloc[:, 0]
holding1=por1.iloc[:, 1]
weight1=holding1.div(holding1.sum())
return1=[]
for m in stock1.tolist():
    return1.append(rt.loc[:,m].tolist())
   
return1=pd.DataFrame(return1).transpose()
port_return1=return1.dot(np.array(weight1).transpose())

current_value=[]
for m in stock1.tolist():
    col=(df1.loc[:, m]).tolist()
    current_value.append(col[-1])

pv=pd.DataFrame(current_value).values.T@pd.DataFrame(holding1).values
pv=float(pv)

#simulate N draws from normal distribution
cov_m=np.cov(np.array(return1).T)
np.random.seed(42)
sim_returns = np.random.multivariate_normal(np.zeros(len(current_value)), cov_m, 10000)

#price each asset from N draws
sim_prices = (1 + sim_returns) * np.array(current_value)
pVals = sim_prices.dot(np.array(holding1))
pVals.sort()

a = int(0.05 * 10000)
VaR = pv - pVals[a]
print("Total Portfolio VaR: {:.4f}".format(VaR))

Total Portfolio VaR: 20004.1749